creation_rules:
  - gcp_kms: projects/quantum-star-435523-g9/locations/northamerica-northeast1/keyRings/my-keyring/cryptoKeys/my-key
    # Specify any file patterns you want to auto-encrypt
    path_regex: '.*\.yml$'
    encrypted_regex: "^(data)$"
