apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: postgres-db
spec: {}
status: {}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-db
  namespace: postgres-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-db
  template:
    metadata:
      labels:
        app: postgres-db
    spec:
      containers:
        - name: postgres
          image: postgres:13
          ports:
            - containerPort: 5432
          envFrom:
            - secretRef:
                name: postgres-secrets
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-db
  namespace: postgres-db
spec:
  selector:
    app: postgres-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP
