apiVersion: v1
data:
  POSTGRES_DB: bXlkYg==
  POSTGRES_PASSWORD: cXdlcnR5
  POSTGRES_USER: c3VwZXJ1c2Vy
kind: Secret
metadata:
  creationTimestamp: null
  name: postgres-secret
  namespace: postgres-db
